# Generated by Django 5.2.4 on 2025-07-28 19:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import places.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the place or establishment.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A detailed description of the location.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geographic coordinates (point).",
                        srid=4326,
                        verbose_name="Coordinates",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="A representative photo of the place.",
                        null=True,
                        upload_to=places.utils.place_photo_path,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="The specific street address of the place.",
                        max_length=255,
                        verbose_name="Address",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="The city where the place is located.",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="The country where the place is located.",
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("moderating", "Moderating"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="The current moderation status of the place.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the place was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update to the place.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who originally created this place.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "ordering": ["-created_at"],
            },
        ),
    ]
