# Generated by Django 5.2.4 on 2025-07-24 15:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import places.utils


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
            },
        ),
        migrations.RemoveField(
            model_name="place",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="The specific street address of the place.",
                max_length=255,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="The city where the place is located.",
                max_length=100,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="The country where the place is located.",
                max_length=100,
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the place was created.",
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who originally created this place.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the location.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Geographic coordinates (point).",
                srid=4326,
                verbose_name="Coordinates",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                help_text="The name of the place or establishment.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="A representative photo of the place.",
                null=True,
                upload_to=places.utils.place_photo_path,
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("moderating", "Moderating"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="The current moderation status of the place.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of the last update to the place.",
                verbose_name="Updated",
            ),
        ),
    ]
