default_language_version:
    python: python

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
    -   id: ruff-format
        types_or: [python, pyi]
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
