# Generated by Django 5.2.4 on 2025-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("moderator", "Moderator"),
                    ("admin", "Admin"),
                ],
                default="user",
                help_text="User role in the system",
                max_length=20,
            ),
        ),
    ]
